apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: tools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: muranura/simple-app:1cce8eeba7c9886013976bf16eb4f44812148e68
        ports:
        - containerPort: 80